import { StyleSheet } from 'react-native';
import { hp } from '../../Hooks/useResponsive';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  scrollContent: { padding: 16 },
  actionButtonsContainer: {
    flexDirection: 'column',
    gap: 10,
    marginBottom: 20,
  },
  actionButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
  },
  whatsappButton: { backgroundColor: '#25D366' },
  secondaryButton: { backgroundColor: '#007bff' },
  actionButtonText: { color: '#fff', fontWeight: '600', fontSize: 15 },
  section: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  label: { fontSize: 14, color: '#666', flex: 1 },
  value: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    textAlign: 'right',
    flex: 1,
  },
  editableContainer: { flex: 1, alignItems: 'flex-end' },
  phoneContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  phoneValue: { fontSize: 14, color: '#25D366', fontWeight: '600' },
  editInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 14,
    textAlign: 'right',
    minWidth: 160,
    backgroundColor: '#fff',
  },
  placeholderText: { color: '#aaa', fontStyle: 'italic' },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: '600',
  },
  attemptedBadge: { backgroundColor: '#fff3cd', color: '#856404' },
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  scrollContent: { padding: 16, paddingTop: hp('0.5') },
  actionButtonsContainer: {
    flexDirection: 'column',
    gap: 10,
    marginBottom: 20,
  },
  actionButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: 'center',
  },
  whatsappButton: { backgroundColor: '#25D366' },
  secondaryButton: { backgroundColor: '#007bff' },
  actionButtonText: { color: '#fff', fontWeight: '600', fontSize: 15 },
  section: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#333',
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  label: { fontSize: 14, color: '#666', flex: 1 },
  value: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
    textAlign: 'right',
    // flex: 1,
  },
  editableContainer: { flex: 1, alignItems: 'flex-end' },
  phoneContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  phoneValue: { fontSize: 14, color: '#25D366', fontWeight: '600' },
  editInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 14,
    textAlign: 'right',
    minWidth: 160,
    backgroundColor: '#fff',
  },
  placeholderText: { color: '#aaa', fontStyle: 'italic' },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: '600',
  },
  attemptedBadge: { backgroundColor: '#fff3cd', color: '#856404' },
  communicationText: {
    fontSize: 13,
    color: '#555',
    lineHeight: 20,
    flex: 1,
    textAlign: 'right',
  },
  collapsibleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  clickToViewButton: {
    backgroundColor: '#007bff',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  clickToViewText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  historyContent: { marginTop: 12 },
  historyLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  callItem: {
    backgroundColor: '#f8f9fa',
    padding: 14,
    borderRadius: 10,
    marginBottom: 8,
  },
  callText: { fontSize: 14, color: '#444' },
  commDetailText: {
    fontSize: 13,
    color: '#555',
    lineHeight: 20,
    textAlign: 'right',
    flex: 1,
  },
  commTextSmall: {
    fontSize: 12,
    color: '#555',
    lineHeight: 18,
  },
  readMoreText: {
    color: '#007bff',
    fontWeight: '600',
    marginTop: 6,
    fontSize: 13,
    textAlign: 'right',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  editButtonText: {
    color: '#007bff',
    fontSize: 15,
    fontWeight: '600',
  },
  editActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#28a745',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 6,
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  cancelButton: {
    padding: 6,
  },
  editInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    textAlign: 'left',
    minWidth: 180,
    backgroundColor: '#fff',
    color: 'black',
  },
  placeholderText: {
    color: '#aaa',
    fontStyle: 'italic',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 10,
    width: '90%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 20,
    color: '#333',
  },
  noteInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    padding: 14,
    textAlignVertical: 'top',
    backgroundColor: '#f9f9f9',
    fontSize: 15,
    color: 'black',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 24,
  },
  button: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
    minWidth: 100,
  },
  cancelBtn: {
    backgroundColor: 'black',
  },
  saveBtn: {
    backgroundColor: '#007bff',
  },
  buttonText: {
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  datePickerBtn: {
    backgroundColor: '#007bff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    marginVertical: 10,
  },
  datePickerText: {
    color: '#fff',
    fontWeight: '600',
  },
});
